#!/bin/bash
# ============================================================================
# wifi-hotspot.sh — Simultaneous WiFi + Hotspot for Intel AX201 (iwlwifi)
#
# This script creates a WiFi hotspot while maintaining an active WiFi
# connection. It works around the Intel AX201 firmware constraint that
# requires both managed (client) and AP (hotspot) interfaces to operate
# on the SAME channel.
#
# Usage:
#   sudo ./wifi-hotspot.sh start [SSID] [PASSWORD]
#   sudo ./wifi-hotspot.sh stop
#   sudo ./wifi-hotspot.sh status
#
# Requirements: hostapd, dnsmasq, iw, iptables
# ============================================================================

set -euo pipefail

# ── Configuration ───────────────────────────────────────────────────────────
DEFAULT_SSID="MyHotspot"
DEFAULT_PASSWORD="hotspot123"
AP_INTERFACE="ap0"
AP_IP="192.168.12.1"
AP_SUBNET="192.168.12.0/24"
AP_DHCP_START="192.168.12.50"
AP_DHCP_END="192.168.12.150"
AP_DHCP_LEASE="12h"
DNS_SERVERS="8.8.8.8,8.8.4.4"

HOSTAPD_CONF="/tmp/wifi-hotspot-hostapd.conf"
DNSMASQ_CONF="/tmp/wifi-hotspot-dnsmasq.conf"
PID_DIR="/tmp/wifi-hotspot"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ── Helper Functions ────────────────────────────────────────────────────────

print_banner() {
    echo -e "${CYAN}${BOLD}"
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║          WiFi + Hotspot Manager (Intel AX201)        ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info()    { echo -e "${GREEN}[✓]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
log_error()   { echo -e "${RED}[✗]${NC} $*"; }
log_step()    { echo -e "${BLUE}[→]${NC} $*"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_dependencies() {
    local missing=()
    for cmd in hostapd dnsmasq iw iptables ip; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies: ${missing[*]}"
        log_info "Install with: sudo dnf install ${missing[*]}"
        exit 1
    fi
}

# Ensure NetworkManager won't manage the AP interface
ensure_nm_unmanaged() {
    local NM_CONF_DIR="/etc/NetworkManager/conf.d"
    local NM_CONF_FILE="$NM_CONF_DIR/99-wifi-hotspot-unmanaged.conf"
    if [[ ! -f "$NM_CONF_FILE" ]]; then
        log_step "Configuring NetworkManager to ignore $AP_INTERFACE..."
        mkdir -p "$NM_CONF_DIR"
        cat > "$NM_CONF_FILE" <<EOF
# Auto-generated by wifi-hotspot.sh
# Prevents NetworkManager from managing the AP interface
[keyfile]
unmanaged-devices=interface-name:$AP_INTERFACE
EOF
        # Reload NetworkManager config (non-disruptive)
        nmcli general reload conf 2>/dev/null || systemctl reload NetworkManager 2>/dev/null || true
        sleep 1
    fi
    # Also explicitly set unmanaged via nmcli
    nmcli device set "$AP_INTERFACE" managed no 2>/dev/null || true
}

# Robustly remove a stale AP interface
cleanup_ap_interface() {
    if ! ip link show "$AP_INTERFACE" &>/dev/null; then
        return 0  # Interface doesn't exist, nothing to do
    fi

    log_step "Removing stale AP interface $AP_INTERFACE..."

    # Step 1: Tell NetworkManager to release the interface
    nmcli device set "$AP_INTERFACE" managed no 2>/dev/null || true
    nmcli device disconnect "$AP_INTERFACE" 2>/dev/null || true

    # Step 2: Bring the interface down
    ip link set "$AP_INTERFACE" down 2>/dev/null || true
    ip addr flush dev "$AP_INTERFACE" 2>/dev/null || true
    sleep 0.5

    # Step 3: Delete using iw first, then fall back to ip link
    if ! iw dev "$AP_INTERFACE" del 2>/dev/null; then
        ip link delete "$AP_INTERFACE" 2>/dev/null || true
    fi

    # Step 4: Wait and verify deletion (up to 3 seconds)
    local retries=6
    while ip link show "$AP_INTERFACE" &>/dev/null && [[ $retries -gt 0 ]]; do
        sleep 0.5
        retries=$((retries - 1))
        # Try again if still present
        iw dev "$AP_INTERFACE" del 2>/dev/null || ip link delete "$AP_INTERFACE" 2>/dev/null || true
    done

    if ip link show "$AP_INTERFACE" &>/dev/null; then
        log_warn "Could not fully remove $AP_INTERFACE, will attempt to reuse it"
    else
        log_info "Stale $AP_INTERFACE removed successfully"
    fi
}

# Find the primary WiFi interface (managed mode, connected)
find_wifi_interface() {
    local iface
    iface=$(iw dev 2>/dev/null | awk '/Interface/{iface=$2} /type managed/{print iface}' | head -1)
    if [[ -z "$iface" ]]; then
        log_error "No WiFi interface in managed mode found"
        exit 1
    fi
    echo "$iface"
}

# Get the channel the WiFi client is currently using
get_current_channel() {
    local iface="$1"
    local channel
    channel=$(iw dev "$iface" info 2>/dev/null | grep -oP 'channel \K[0-9]+')
    if [[ -z "$channel" ]]; then
        log_error "Could not determine current WiFi channel for $iface"
        log_error "Make sure you are connected to a WiFi network first"
        exit 1
    fi
    echo "$channel"
}

# Get the SSID the WiFi client is connected to
get_current_ssid() {
    local iface="$1"
    iw dev "$iface" info 2>/dev/null | grep -oP 'ssid \K.*' || echo "unknown"
}

# Get the frequency band from channel number
get_hw_mode() {
    local channel="$1"
    if [[ "$channel" -le 14 ]]; then
        echo "g"  # 2.4 GHz
    else
        echo "a"  # 5 GHz
    fi
}

is_running() {
    [[ -d "$PID_DIR" ]] && [[ -f "$PID_DIR/hostapd.pid" || -f "$PID_DIR/dnsmasq.pid" ]]
}

# ── Core Functions ──────────────────────────────────────────────────────────

do_start() {
    local ssid="${1:-$DEFAULT_SSID}"
    local password="${2:-$DEFAULT_PASSWORD}"

    print_banner

    # Preflight checks
    if is_running; then
        log_warn "Hotspot appears to be already running. Stop it first with: sudo $0 stop"
        exit 1
    fi

    if [[ ${#password} -lt 8 ]]; then
        log_error "Password must be at least 8 characters long"
        exit 1
    fi

    check_dependencies

    # Detect WiFi setup
    local wifi_iface
    wifi_iface=$(find_wifi_interface)
    log_info "WiFi interface: ${BOLD}$wifi_iface${NC}"

    local wifi_ssid
    wifi_ssid=$(get_current_ssid "$wifi_iface")
    log_info "Connected to: ${BOLD}$wifi_ssid${NC}"

    local channel
    channel=$(get_current_channel "$wifi_iface")
    log_info "Current channel: ${BOLD}$channel${NC}"

    local hw_mode
    hw_mode=$(get_hw_mode "$channel")
    log_info "Band: ${BOLD}$([ "$hw_mode" = "g" ] && echo "2.4 GHz" || echo "5 GHz")${NC}"

    echo ""
    log_step "Creating AP interface ${BOLD}$AP_INTERFACE${NC} on channel ${BOLD}$channel${NC}..."

    # Tell NetworkManager to never manage the AP interface
    ensure_nm_unmanaged

    # Remove stale AP interface if it exists
    cleanup_ap_interface

    # Create AP interface
    if ! iw dev "$wifi_iface" interface add "$AP_INTERFACE" type __ap 2>/tmp/wifi-hotspot-iw-err.txt; then
        local iw_err
        iw_err=$(cat /tmp/wifi-hotspot-iw-err.txt)
        # If it failed because ap0 already exists in the right mode, try to reuse
        if ip link show "$AP_INTERFACE" &>/dev/null; then
            log_warn "Interface $AP_INTERFACE already exists, attempting to reconfigure..."
            iw dev "$AP_INTERFACE" set type __ap 2>/dev/null || true
        else
            log_error "Failed to create AP interface: $iw_err"
            exit 2
        fi
    fi
    sleep 1

    # Ensure NetworkManager doesn't grab the new interface
    nmcli device set "$AP_INTERFACE" managed no 2>/dev/null || true

    # Assign a unique MAC address (increment last byte)
    local base_mac
    base_mac=$(cat /sys/class/net/"$wifi_iface"/address)
    local last_byte
    last_byte=$(echo "$base_mac" | awk -F: '{printf "%d", "0x"$6}')
    last_byte=$(( (last_byte + 1) % 256 ))
    local new_mac
    new_mac=$(echo "$base_mac" | awk -F: -v lb="$(printf '%02x' $last_byte)" '{OFS=":"; $6=lb; print}')
    ip link set dev "$AP_INTERFACE" address "$new_mac"

    # Bring up the AP interface with an IP
    ip addr flush dev "$AP_INTERFACE" 2>/dev/null || true
    ip addr add "${AP_IP}/24" dev "$AP_INTERFACE"
    ip link set "$AP_INTERFACE" up
    log_info "AP interface ${BOLD}$AP_INTERFACE${NC} is up with IP ${BOLD}$AP_IP${NC}"

    # Create hostapd configuration
    log_step "Configuring hostapd..."
    cat > "$HOSTAPD_CONF" <<EOF
# Auto-generated by wifi-hotspot.sh
interface=$AP_INTERFACE
driver=nl80211
ssid=$ssid
hw_mode=$hw_mode
channel=$channel
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=$password
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

    # Create dnsmasq configuration
    log_step "Configuring dnsmasq..."
    cat > "$DNSMASQ_CONF" <<EOF
# Auto-generated by wifi-hotspot.sh
interface=$AP_INTERFACE
bind-interfaces
dhcp-range=$AP_DHCP_START,$AP_DHCP_END,$AP_DHCP_LEASE
dhcp-option=option:router,$AP_IP
dhcp-option=option:dns-server,$DNS_SERVERS
log-dhcp
EOF

    # Enable IP forwarding
    log_step "Enabling IP forwarding..."
    sysctl -w net.ipv4.ip_forward=1 >/dev/null

    # Setup NAT with iptables
    log_step "Setting up NAT (iptables)..."
    iptables -t nat -A POSTROUTING -o "$wifi_iface" -j MASQUERADE
    iptables -A FORWARD -i "$AP_INTERFACE" -o "$wifi_iface" -j ACCEPT
    iptables -A FORWARD -i "$wifi_iface" -o "$AP_INTERFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT

    # Create PID directory
    mkdir -p "$PID_DIR"

    # Save config for teardown
    echo "$wifi_iface" > "$PID_DIR/wifi_iface"

    # Stop any existing hostapd/dnsmasq bound to our interface
    pkill -f "hostapd.*$HOSTAPD_CONF" 2>/dev/null || true
    pkill -f "dnsmasq.*$DNSMASQ_CONF" 2>/dev/null || true
    sleep 0.5

    # Start dnsmasq
    log_step "Starting dnsmasq..."
    dnsmasq -C "$DNSMASQ_CONF" --pid-file="$PID_DIR/dnsmasq.pid" --log-facility=/tmp/wifi-hotspot-dnsmasq.log
    log_info "dnsmasq started (PID: $(cat "$PID_DIR/dnsmasq.pid"))"

    # Start hostapd
    log_step "Starting hostapd..."
    hostapd -B -P "$PID_DIR/hostapd.pid" "$HOSTAPD_CONF" -f /tmp/wifi-hotspot-hostapd.log
    sleep 2

    if [[ -f "$PID_DIR/hostapd.pid" ]] && kill -0 "$(cat "$PID_DIR/hostapd.pid")" 2>/dev/null; then
        log_info "hostapd started (PID: $(cat "$PID_DIR/hostapd.pid"))"
    else
        log_error "hostapd failed to start! Check /tmp/wifi-hotspot-hostapd.log"
        log_warn "Cleaning up..."
        do_stop
        exit 1
    fi

    # Verify WiFi is still connected
    echo ""
    if iw dev "$wifi_iface" info 2>/dev/null | grep -q "ssid"; then
        local still_ssid
        still_ssid=$(get_current_ssid "$wifi_iface")
        log_info "WiFi still connected to: ${BOLD}$still_ssid${NC} ✓"
    else
        log_warn "WiFi connection may have dropped. Reconnecting..."
        nmcli device connect "$wifi_iface" 2>/dev/null || true
    fi

    echo ""
    echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║              Hotspot is ACTIVE!                      ║${NC}"
    echo -e "${GREEN}${BOLD}╠══════════════════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  SSID:      ${CYAN}${BOLD}$ssid${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  Password:  ${CYAN}${BOLD}$password${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  Channel:   ${CYAN}${BOLD}$channel${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  Gateway:   ${CYAN}${BOLD}$AP_IP${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  Internet:  ${CYAN}${BOLD}via $wifi_iface → $wifi_ssid${NC}"
    echo -e "${GREEN}${BOLD}╠══════════════════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}${BOLD}║${NC}  Stop with: ${YELLOW}sudo $0 stop${NC}"
    echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
}

do_stop() {
    print_banner
    log_step "Stopping hotspot..."

    local wifi_iface=""
    if [[ -f "$PID_DIR/wifi_iface" ]]; then
        wifi_iface=$(cat "$PID_DIR/wifi_iface")
    else
        wifi_iface=$(find_wifi_interface 2>/dev/null || echo "wlp0s20f3")
    fi

    # Stop hostapd
    if [[ -f "$PID_DIR/hostapd.pid" ]]; then
        local pid
        pid=$(cat "$PID_DIR/hostapd.pid")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null
            log_info "Stopped hostapd (PID: $pid)"
        fi
    fi
    pkill -f "hostapd.*$HOSTAPD_CONF" 2>/dev/null || true

    # Stop dnsmasq
    if [[ -f "$PID_DIR/dnsmasq.pid" ]]; then
        local pid
        pid=$(cat "$PID_DIR/dnsmasq.pid")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null
            log_info "Stopped dnsmasq (PID: $pid)"
        fi
    fi
    pkill -f "dnsmasq.*$DNSMASQ_CONF" 2>/dev/null || true

    # Remove iptables rules
    log_step "Removing NAT rules..."
    iptables -t nat -D POSTROUTING -o "$wifi_iface" -j MASQUERADE 2>/dev/null || true
    iptables -D FORWARD -i "$AP_INTERFACE" -o "$wifi_iface" -j ACCEPT 2>/dev/null || true
    iptables -D FORWARD -i "$wifi_iface" -o "$AP_INTERFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
    log_info "NAT rules removed"

    # Remove AP interface (use robust cleanup)
    cleanup_ap_interface

    # Cleanup temp files
    rm -rf "$PID_DIR"
    rm -f "$HOSTAPD_CONF" "$DNSMASQ_CONF"
    rm -f /tmp/wifi-hotspot-hostapd.log /tmp/wifi-hotspot-dnsmasq.log

    echo ""
    log_info "${BOLD}Hotspot stopped cleanly.${NC}"
}

do_status() {
    print_banner

    # Check if running
    if ! is_running; then
        log_warn "Hotspot is ${BOLD}NOT running${NC}"
        echo ""
        echo -e "  Start with: ${YELLOW}sudo $0 start [SSID] [PASSWORD]${NC}"
        return
    fi

    log_info "Hotspot is ${GREEN}${BOLD}ACTIVE${NC}"
    echo ""

    # WiFi client info
    local wifi_iface
    wifi_iface=$(find_wifi_interface 2>/dev/null || echo "unknown")
    echo -e "  ${BOLD}WiFi Client:${NC}"
    echo -e "    Interface: $wifi_iface"
    echo -e "    SSID:      $(get_current_ssid "$wifi_iface")"
    echo -e "    Channel:   $(get_current_channel "$wifi_iface")"
    echo ""

    # AP info
    echo -e "  ${BOLD}Hotspot (AP):${NC}"
    if ip link show "$AP_INTERFACE" &>/dev/null; then
        echo -e "    Interface: $AP_INTERFACE"
        echo -e "    IP:        $(ip addr show "$AP_INTERFACE" 2>/dev/null | grep -oP 'inet \K[0-9.]+' || echo 'N/A')"
        local ap_ssid
        ap_ssid=$(grep '^ssid=' "$HOSTAPD_CONF" 2>/dev/null | cut -d= -f2 || echo "N/A")
        echo -e "    SSID:      $ap_ssid"
    else
        echo -e "    ${RED}AP interface not found${NC}"
    fi
    echo ""

    # Process info
    echo -e "  ${BOLD}Processes:${NC}"
    if [[ -f "$PID_DIR/hostapd.pid" ]] && kill -0 "$(cat "$PID_DIR/hostapd.pid")" 2>/dev/null; then
        echo -e "    hostapd: ${GREEN}running${NC} (PID: $(cat "$PID_DIR/hostapd.pid"))"
    else
        echo -e "    hostapd: ${RED}not running${NC}"
    fi
    if [[ -f "$PID_DIR/dnsmasq.pid" ]] && kill -0 "$(cat "$PID_DIR/dnsmasq.pid")" 2>/dev/null; then
        echo -e "    dnsmasq: ${GREEN}running${NC} (PID: $(cat "$PID_DIR/dnsmasq.pid"))"
    else
        echo -e "    dnsmasq: ${RED}not running${NC}"
    fi
    echo ""

    # Connected clients
    echo -e "  ${BOLD}Connected Clients:${NC}"
    local clients
    clients=$(iw dev "$AP_INTERFACE" station dump 2>/dev/null | grep -c "Station" || echo "0")
    echo -e "    Count: $clients"
    if [[ "$clients" -gt 0 ]]; then
        iw dev "$AP_INTERFACE" station dump 2>/dev/null | grep "Station\|signal\|rx bytes\|tx bytes" | sed 's/^/    /'
    fi
    echo ""

    # Internet connectivity
    echo -e "  ${BOLD}Internet:${NC}"
    if ping -c 1 -W 2 8.8.8.8 &>/dev/null; then
        echo -e "    Connectivity: ${GREEN}OK${NC}"
    else
        echo -e "    Connectivity: ${RED}DOWN${NC}"
    fi
}

# ── Main ────────────────────────────────────────────────────────────────────

usage() {
    echo -e "${BOLD}Usage:${NC} sudo $0 {start|stop|status} [SSID] [PASSWORD]"
    echo ""
    echo -e "  ${BOLD}start${NC} [SSID] [PASSWORD]  Start hotspot (default: $DEFAULT_SSID / $DEFAULT_PASSWORD)"
    echo -e "  ${BOLD}stop${NC}                     Stop hotspot and clean up"
    echo -e "  ${BOLD}status${NC}                   Show current hotspot status"
    echo ""
    echo -e "  ${BOLD}Examples:${NC}"
    echo "    sudo $0 start"
    echo "    sudo $0 start MyNetwork SecurePass123"
    echo "    sudo $0 stop"
    echo "    sudo $0 status"
}

main() {
    case "${1:-}" in
        start)
            check_root
            do_start "${2:-}" "${3:-}"
            ;;
        stop)
            check_root
            do_stop
            ;;
        status)
            check_root
            do_status
            ;;
        -h|--help)
            print_banner
            usage
            ;;
        *)
            print_banner
            usage
            exit 1
            ;;
    esac
}

main "$@"
